version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db123
  app:
    image: my-node-app
    ports:
      - 13000:3000